# Generated by Django 4.2.16 on 2024-11-13 08:51

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0035_alter_staffgroup_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='registration_text',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ user.full_name }}<br><br>Thank you for registering for {{ request.press.name }}. You can confirm your account at the following link:</p><p><br><a href="{{ core_confirm_account_url }}">{{ core_confirm_account_url }}</a><br>{{request.press.name}}</p>', null=True),
        ),
    ]
