# Generated by Django 4.2.15 on 2024-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_merge_20240819_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrole',
            options={'ordering': ('journal', 'role')},
        ),
        migrations.AddField(
            model_name='account',
            name='banned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='citizen_deactive_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_citizen_active',
            field=models.BooleanField(default=False),
        ),
    ]
