# Generated by Django 4.2.15 on 2024-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_accountrole_options_account_banned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='citizen_deactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
