# Generated by Django 4.2.16 on 2024-11-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_account_banned_at_and_more'),
        ('core', '0099_alter_accountrole_options'),
    ]

    operations = [
    ]
