# Generated by Django 4.2.16 on 2024-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_merge_20241105_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='college_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='account',
            name='university_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
