# Generated by Django 4.2.16 on 2024-11-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_account_college_id_account_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ban_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_user_author',
            field=models.BooleanField(default=False),
        ),
    ]
