# Generated by Django 4.2.16 on 2024-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20241122_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='osp_role',
            field=models.CharField(choices=[('user', 'user'), ('super_admin', 'super_admin'), ('citizen_support', 'citizen_support'), ('knowledge_support', 'knowledge_support'), ('chief_editor', 'chief_editor'), ('editor', 'editor'), ('proof_reader', 'proof_reader'), ('science_communicator', 'science_communicator')], default='user', max_length=20, verbose_name='OSP Role'),
        ),
    ]
